services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    environment:
      - ASR_MODEL=small
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]

  backend:
    build: .
    init: true
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ./diffusert:/workspace/diffusert/
      - engines:/engines
      - onnx:/onnx
      - ~/.cache/huggingface:/root/.cache/huggingface
    working_dir: /workspace/diffusert
    ports:
      - 8080:8080
    entrypoint: "sleep infinity"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]

volumes:
  engines:
  onnx:
