
x-base: &x-base
  init: true
  environment:
    - LOG_LEVEL=INFO
  volumes:
    - ./diffusert:/workspace/diffusert/
    - engines:/engines
    - onnx:/onnx
    - ~/.cache/huggingface:/root/.cache/huggingface
  working_dir: /workspace/diffusert

x-gpu: &x-gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            capabilities: ["gpu"]

services:
  whisper:
    <<: *x-gpu    
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    environment:
      - ASR_MODEL=small
    profiles:
      - production
      - dev

  frontend: &frontend
    image: nginx
    volumes:
      - ./public:/usr/share/nginx/html
      - ./configs/nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80
    environment:
      - BACKEND_HOST=backend
    profiles:
      - production

  frontend-dev:
    <<: *frontend
    environment:
      - BACKEND_HOST=backend-dev
    profiles:
      - dev

  backend: &backend
    <<: [*x-base,*x-gpu]
    build: .
    entrypoint: "python server.py"
    ports:
      - 8080:8080
    profiles:
      - production
  
  backend-dev:
    <<: *backend
    image: videosd-backend
    entrypoint: "sleep infinity"
    profiles:
      - dev

  compile:
    <<: *backend
    image: videosd-backend
    entrypoint: "python compile.py"
    profiles:
      - compile

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=204.15.42.207 #optional
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=8.8.8.8 #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:

      - ./wg/config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

volumes:
  engines:
  onnx:
