
x-base: &x-base
  init: true
  environment:
    - LOG_LEVEL=INFO
  volumes:
    - ./diffusert:/workspace/diffusert/
    - engines:/engines
    - onnx:/onnx
    - ~/.cache/huggingface:/root/.cache/huggingface
  working_dir: /workspace/diffusert

x-gpu: &x-gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ["1"]
            capabilities: ["gpu"]

services:
  whisper:
    <<: *x-gpu    
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    environment:
      - ASR_MODEL=small
    profiles:
      - production
      - dev

  frontend: &frontend
    image: nginx
    volumes:
      - ./public:/usr/share/nginx/html
      - ./configs/nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80
    environment:
      - BACKEND_HOST=backend
    profiles:
      - production

  frontend-dev:
    <<: *frontend
    environment:
      - BACKEND_HOST=backend-dev
    profiles:
      - dev

  backend: &backend
    <<: *x-base
    <<: *x-gpu
    build: .
    entrypoint: "python server.py"
    ports:
      - 8080:8080
    profiles:
      - production
  
  backend-dev:
    <<: *backend
    image: videosd-backend
    entrypoint: "sleep infinity"
    profiles:
      - dev

  compile:
    <<: *backend
    image: videosd-backend
    entrypoint: "python compile.py"
    profiles:
      - compile

volumes:
  engines:
  onnx:
