services:
  builder:

    image: voltaml:latest
    init: true
    environment:
      - LOG_LEVEL=INFO
    # stdin_open: true # docker run -i
    # tty: true 
    volumes:
      - ./diffusert:/workspace/diffusert/
      - engines:/engines
      - onnx:/onnx
      - /c/users/giova/.cache/huggingface:/root/.cache/huggingface
    ports:
      - 8080:8080
    entrypoint: "sleep infinity"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]

volumes:
  engines:
  onnx:
